PHP 8.5: Function curl_close() is deprecated since 8.5
DeprecatedException: Function curl_close() is deprecated since 8.5, as it has no effect since PHP 8.0