use cweagans/composer-patches (instead of vaimo/composer-patches)
because with vaimo/composer-patches:
- there is https://github.com/vaimo/composer-patches/issues/115 which refrains
  from using it on php 7.0 7.1 & 7.2
- patching randomly fails with weird errors:

Processing patches configuration
  - Applying patches for codeigniter/framework (2)
    ~ kalkun-sms/kalkun: patches/Codeigniter_Framework/v3.1.13/10-php82_support.patch [NEW]
      Add support for PHP 8.2 (part1)
    ~ kalkun-sms/kalkun: patches/Codeigniter_Framework/v3.1.13/10-php82_support-part2.patch [NEW]
      Add support for PHP 8.2 (part2)

Error: Could not delete /home/runner/work/Kalkun/Kalkun/vendor/kenjis/ci-phpunit-test/CONTRIBUTING.md:

In Filesystem.php line 288:

  Could not delete /home/runner/work/Kalkun/Kalkun/vendor/kenjis/ci-phpunit-t
  est/CONTRIBUTING.md:

or

Processing patches configuration
  - Applying patches for codeigniter/framework (2)
    ~ kalkun-sms/kalkun: patches/Codeigniter_Framework/v3.1.13/10-php82_support.patch [NEW]
      Add support for PHP 8.2 (part1)
    ~ kalkun-sms/kalkun: patches/Codeigniter_Framework/v3.1.13/10-php82_support-part2.patch [NEW]
      Add support for PHP 8.2 (part2)

Error: Could not delete /home/runner/work/Kalkun/Kalkun/vendor/kenjis/ci-phpunit-test/.gitignore:

In Filesystem.php line 288:

  Could not delete /home/runner/work/Kalkun/Kalkun/vendor/kenjis/ci-phpunit-t
  est/.gitignore: