b8/storage/storage_base constructor: support php < 7.2
PHP 7.1 reports this

TypeError: Argument 2 passed to b8\storage\storage_base::__construct() must be an instance of b8\storage\object, instance of b8\degenerator\standard given.

Likely because support for 'object' type in type declarations has been added in PHP 7.2 https://www.php.net/manual/en/language.types.declarations.php