use 'require' instead of 'require_once' to load database.php config file
Otherwise, with ci-phpunit-test, 1st test passes, and next ones will report
ErrorException: Undefined variable $db