remove 'string' typehint in b8
Because it is not supported in PHP5.6. Only since PHP 7.0

ErrorException: Argument 1 passed to b8\lexer\standard::get_tokens() must be an instance of b8\lexer\string, string given