don't autoload Phonebook_model
It causes issues with ci-phpunit-test.
Error reported is:
ErrorException: Undefined property: Kalkun::
(inside controller/Kalkun.php::index()